# Generated by Django 5.0.6 on 2024-05-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_name', models.CharField(max_length=100)),
                ('Game_description', models.CharField(max_length=500)),
                ('Game_dev', models.CharField(max_length=100)),
                ('dev_email', models.EmailField(max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
