# Generated by Django 5.0.6 on 2024-05-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='Game_engine',
            field=models.CharField(default=2, max_length=100, verbose_name='Motor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='Game_lang',
            field=models.CharField(default='-', max_length=100, verbose_name='Lenguaje utilizado'),
        ),
        migrations.AddField(
            model_name='games',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='game'),
        ),
        migrations.AlterField(
            model_name='games',
            name='Game_description',
            field=models.CharField(max_length=500, verbose_name='Descripción del juego'),
        ),
        migrations.AlterField(
            model_name='games',
            name='Game_dev',
            field=models.CharField(max_length=100, verbose_name='Nombre del desarrollador'),
        ),
        migrations.AlterField(
            model_name='games',
            name='Game_name',
            field=models.CharField(default='-', max_length=100, verbose_name='Nombre del juego'),
        ),
        migrations.AlterField(
            model_name='games',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='games',
            name='dev_email',
            field=models.EmailField(max_length=50, verbose_name='email del desarrollador'),
        ),
    ]
