# Generated by Django 5.0.6 on 2024-05-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_games_game_engine_games_game_lang_games_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='Game_lang',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lenguaje utilizado'),
        ),
        migrations.AlterField(
            model_name='games',
            name='Game_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del juego'),
        ),
    ]
