# Generated by Django 5.0.6 on 2024-05-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_games_game_lang_alter_games_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='Game_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link del juego'),
        ),
    ]
